
sudo: required
services: 
   - docker


before_install:
   - docker build -t 7066409406/docker-reach -f Dockerfile.dev .

script:
   - docker run 7066409406/docker-reach npm run test -- --coverage
   
